name: quiz-walk
services:
  frontend:
    build: ./quiz-frontend
    volumes:
      - ./quiz-frontend:/app
      - /app/node_modules

    ports:
      - 3000:3000

    environment:
      - CHOKIDAR_USEPOLLING=true

  quiz-service:
    build: ./quiz-backend/quiz-service
    volumes:
      - ./quiz-backend/quiz-service:/app
      - /app/node_modules
    ports: 
    - 8000:8000