name: quiz-walk
services:
  frontend:
    build: ./quiz-frontend
    volumes:
      - ./quiz-frontend:/app
      - /app/node_modules

    ports:
      - 3000:3000

    environment:
      - CHOKIDAR_USEPOLLING=true

  quiz-service:
    build: ./quiz-backend/quiz-service
    volumes:
      - ./quiz-backend/quiz-service:/app
      - /app/node_modules
    ports: 
    - 8000:8000

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
      - mongo-data:/data/db
      
volumes:
  mongo-data: